name: Go App CI/CD


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE: skinpro/skin-pro-backend
  K8S_APP_DIR: ~/app/k8s


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            skinpro/skin-pro-backend:latest
            skinpro/skin-pro-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy k8s folder
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.K8S_MASTER_HOST }}
          username: ${{ secrets.K8S_MASTER_USER }}
          key: ${{ secrets.K8S_MASTER_SSH_KEY }}
          source: k8s/*
          target: ${{ env.K8S_APP_DIR }}
          strip_components: 1

      - name: Copy .env to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K8S_MASTER_HOST }}
          username: ${{ secrets.K8S_MASTER_USER }}
          key: ${{ secrets.K8S_MASTER_SSH_KEY }}
          script: |
            # Создаем директорию
            mkdir -p ${{ env.K8S_APP_DIR }}
            # Копируем k8s/ из репозитория
            cp -r $GITHUB_WORKSPACE/k8s ${{ env.K8S_APP_DIR }}/
            # Создаем .env из секрета
            cat << 'EOF' > ${{ env.K8S_APP_DIR }}/.env
            ${{ secrets.ENV_FILE }}
            EOF
            # Проверяем, что всё на месте
            ls -la ${{ env.K8S_APP_DIR }}


      - name: Apply Kubernetes manifests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K8S_MASTER_HOST }}
          username: ${{ secrets.K8S_MASTER_USER }}
          key: ${{ secrets.K8S_MASTER_SSH_KEY }}
          script: |
            set -e
            # Применяем deployment и service
            kubectl apply -f ${{ env.K8S_APP_DIR }}/deployment.yaml
            kubectl apply -f ${{ env.K8S_APP_DIR }}/service.yaml
            
            # Принудительно обновляем поды (изменяет аннотацию)
            kubectl rollout restart deployment/skin-pro-app
            
            # Ждем готовности deployment
            kubectl rollout status deployment/skin-pro-app --timeout=60s
            
            # Показываем статус
            kubectl get pods,services -o wide
